# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

# app_rating_config_path("./fastlane/metadata/rating_config.json")

app_review_information(
  first_name: ENV["DELIVER_FIRST_NAME"],
  last_name: ENV["DELIVER_LAST_NAME"],
  phone_number: ENV["DELIVER_PHONE_NUMBER"],
  email_address: ENV["DELIVER_EMAIL_ADDRESS"]
)

automatic_release(false)
copyright(ENV["COPYRIGHT"])
force(true)
phased_release(false)
primary_category("Games")
price_tier(0)

privacy_url({
  'en-US' => "#{ENV["GITHUB_LINK"]}/privacy_policy.html"
})

run_precheck_before_submit(false)
skip_app_version_update(true)
skip_binary_upload(true)
skip_screenshots(true)

support_url({
  'en-US' => ENV["GITHUB_REPO"]
})

submission_information({
  add_id_info_serves_ads: true,
  add_id_info_tracks_action: true,
  content_rights_has_rights: true,
  export_compliance_uses_encryption: false,
  export_compliance_compliance_required: false,
  export_compliance_contains_proprietary_cryptography: false,
  export_compliance_contains_third_party_cryptography: false,
  
})

submit_for_review(false)

trade_representative_contact_information(
  first_name: ENV["DELIVER_FIRST_NAME"],
  last_name: ENV["DELIVER_LAST_NAME"],
  address_line1: ENV["DELIVER_ADDRESS_LINE_1"],
  address_line2: ENV["DELIVER_ADDRESS_LINE_2"],
  address_line3: ENV["DELIVER_ADDRESS_LINE_3"],
  city_name: ENV["DELIVER_CITY_NAME"],
  state: ENV["DELIVER_STATE"],
  country: ENV["DELIVER_COUNTRY"],
  postal_code: ENV["DELIVER_POSTAL_CODE"],
  phone_number: ENV["DELIVER_PHONE_NUMBER"],
  email_address: ENV["DELIVER_EMAIL_ADDRESS"]
)