baseurl: \/MineBleeper

collections:
  contributors:
    output: true

defaults:
  - scope:
      path: ""
      type: "contributors"
    values:
      layout: "contributor"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "support"
    values:
      layout: "support"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
